language: java
install: true
jdk:
- oraclejdk8
before_install:
- nohup bash -c "cd 3_cws_arquitectura_skel/data/ && java -classpath ../lib/hsqldb.jar org.hsqldb.Server"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start